[package]
name = "bdpi_tester"
version = "1.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["socks"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
futures = "0.3"
