[package]
name = "bdpi_tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["socks", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
chrono = { version = "0.4"}
